import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/navbar";

export const metadata = {
  title: "Market",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full flex flex-col justify-start">
      {/* <Navbar /> */}
      <Navbar />

      {/* main  */}
      <main className=" h-[calc(100dvh-170px)] overflow-y-auto bg-white ">
        {children}
      </main>

      {/*  <Footer /> */}
      <Footer />
    </div>
  );
}
